### PR TITLE
New getting started Loan app project

### PR DESCRIPTION
**Pull request by ibek**
This is a starter project for the getting started guide in BPM. It includes few assets so that the guide can contain only the important and non-repetitive parts that we think they should learn.

### CODE REVIEW

**Comment by mbiarnes** [comment]
ok to test

**Comment by ibek** [comment]
Hi @AntStephenson , it happened again, will we see you eat your hat? :rofl: ref: https://github.com/kiegroup/kie-wb-playground/pull/50#issuecomment-379720194

**Comment by AntStephenson** [comment]
@ibek damn it, I should of specified "if it fails because of the same error" :(

**Comment by AntStephenson** [comment]
img_20180409_143017__01

.. as promised.

**Comment by AntStephenson** [comment]
@ibek You can also see the reason it failed this time here:

https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-playground-pullrequests-7.7.x/4/console

**Pull request merged**
