### PR TITLE
New getting started Loan app project

### PR DESCRIPTION
**Pull request by ibek**
This is a starter project for the getting started guide in BPM. It includes few assets so that the guide can contain only the important and non-repetitive parts that we think they should learn.

### CODE REVIEW

**Comment by krisv** [comment]
ok to test

**Comment by krisv** [comment]
ok to test

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
OK to test

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
thanX for this information @AntStephenson 
@ibek : would you be so kind and close this PR and re-open another one?

**Pull request closed without merging**
