### PR TITLE
New getting started Loan app project

### PR DESCRIPTION
**Pull request by ibek**
This is a starter project for the getting started guide in BPM. It includes few assets so that the guide can contain only the important and non-repetitive parts that we think they should learn.

### CODE REVIEW

**Comment by ibek** [comment]
This is a cherry-pick for 7.7.x branch from https://github.com/kiegroup/kie-wb-playground/pull/50

**Comment by krisv** [comment]
ok to test

**Comment by krisv** [comment]
ok to test

**Comment by mbiarnes** [comment]
look #50 
@ibek : would you be so kind and close this PR and re-open another one?

**Pull request closed without merging**
