### PR TITLE
PLANNER-590: Workbench: Dinnerparty example should work out of the box

### PR DESCRIPTION
**Pull request by mcimbora**
Add a simplified dinnerparty example leveraging drl-based score rules and a decision table to define scoring function.

@ge0ffrey @yurloc Would you mind taking a look? Thanks in advance

### CODE REVIEW

**Comment by yurloc** [comment]
The NeighborTable seems to cause error during indexing. If there's a problem with the table, it would be nice to fix that before merging but I think it might be a bug in the decision table model.
```
21:41:34,601 ERROR [org.kie.workbench.common.services.refactoring.backend.server.indexing.AbstractFileIndexer] (EJB default - 7) Unable to index 'default://master@myrepo/dinnerparty/src/main/resources/dinnerparty/dinnerparty/NeighborTable.gdst'.: java.lang.NullPointerException
	at org.drools.workbench.screens.guided.dtable.backend.server.indexing.GuidedRuleModelIndexVisitor.getFullyQualifiedClassName(GuidedRuleModelIndexVisitor.java:253)
	at org.drools.workbench.screens.guided.dtable.backend.server.indexing.GuidedRuleModelIndexVisitor.visitSingleFieldConstraint(GuidedRuleModelIndexVisitor.java:212)
	at org.drools.workbench.screens.guided.dtable.backend.server.indexing.GuidedRuleModelIndexVisitor.visit(GuidedRuleModelIndexVisitor.java:82)
	at org.drools.workbench.screens.guided.dtable.backend.server.indexing.GuidedRuleModelIndexVisitor.visitFactPattern(GuidedRuleModelIndexVisitor.java:145)
	at org.drools.workbench.screens.guided.dtable.backend.server.indexing.GuidedRuleModelIndexVisitor.visit(GuidedRuleModelIndexVisitor.java:76)
	at org.drools.workbench.screens.guided.dtable.backend.server.indexing.GuidedRuleModelIndexVisitor.visitRuleModel(GuidedRuleModelIndexVisitor.java:180)
	at org.drools.workbench.screens.guided.dtable.backend.server.indexing.GuidedRuleModelIndexVisitor.visit(GuidedRuleModelIndexVisitor.java:72)
	at org.drools.workbench.screens.guided.dtable.backend.server.indexing.GuidedRuleModelIndexVisitor.visit(GuidedRuleModelIndexVisitor.java:66)
	at org.drools.workbench.screens.guided.dtable.backend.server.indexing.GuidedDecisionTableModelIndexVisitor.visit(GuidedDecisionTableModelIndexVisitor.java:173)
	at org.drools.workbench.screens.guided.dtable.backend.server.indexing.GuidedDecisionTableModelIndexVisitor.visit(GuidedDecisionTableModelIndexVisitor.java:79)
	at org.drools.workbench.screens.guided.dtable.backend.server.indexing.GuidedDecisionTableModelIndexVisitor.visit(GuidedDecisionTableModelIndexVisitor.java:102)
	at org.drools.workbench.screens.guided.dtable.backend.server.indexing.GuidedDecisionTableModelIndexVisitor.visit(GuidedDecisionTableModelIndexVisitor.java:66)
	at org.drools.workbench.screens.guided.dtable.backend.server.indexing.GuidedDecisionTableFileIndexer.fillIndexBuilder(GuidedDecisionTableFileIndexer.java:51)
	at org.kie.workbench.common.services.refactoring.backend.server.indexing.AbstractFileIndexer.toKObject(AbstractFileIndexer.java:78)
```

Otherwise looks good to me.

**Comment by manstis** [comment]
Looks like a bug in the Guided Decision Table Indexer. Can you please open a GUVNOR JIRA and include the relevant information.

**Comment by yurloc** [comment]
https://issues.jboss.org/browse/GUVNOR-3244

**Comment by manstis** [comment]
Merged on the basis that @yurloc approved (see comments above).

https://issues.jboss.org/browse/GUVNOR-3244 has also been resolved.

**Pull request merged**
