### PR TITLE
[7.7.x] JBPM-7124: KIE Playground examples - Move to the use of Stunner as the default process editor

### PR DESCRIPTION
**Pull request by pefernan**
Renamed assets to be used by new designer.

@romartin @mswiderski could you please take a look?

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
@pefernan I don't think you need full downstream build here.. it's last repository so changes here don't impact any other repo isn't it?

**Comment by pefernan** [comment]
@mswiderski well yes, I was trying it to make sure that there are no integration tests broken because of these change. But totally agree to merge it if you think it is right ;)

**Comment by pefernan** [comment]
@mswiderski no greens today... should I merge then?

**Comment by romartin** [comment]
@mswiderski well but doing the full downstream we can test the generated war this way... :+1:

**Comment by romartin** [comment]
Tested and examples are fine. Merging. Thx!

**Pull request merged**
