### PR TITLE
JBPM-5767 - Add itorders Case Management example project to kie-wb-pl…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…ayground

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@mswiderski mind checking if I haven't missed anything or any file we don't need. Thanks.

**Comment by bsremac** [comment]
@cristianonicolai I believe there should be only one .wid file per project.
Have a look at:
https://issues.jboss.org/browse/RHBPMS-479

**Comment by cristianonicolai** [comment]
@bsremac thanks, I've removed the extra .wid files.

**Comment by cristianonicolai** [comment]
@mswiderski I also noticed that we had a few .wid files when creating a case project. I'm wondering if we should only add one based on @bsremac's comment.

**Comment by mswiderski** [comment]
@cristianonicolai when I did the case project then this was a must otherwise case def in another package didn't see new stuff like milestones. If that is now solved and will work  then we should remove duplicates

**Comment by cristianonicolai** [comment]
@mswiderski fair enough, I can get a PR for so we verify if the problem is solved. Does this one looks good to you?

**Comment by mswiderski** [comment]
looks good!

**Pull request merged**
