### PR TITLE
Replace getstarted-loan with complete mortgage-process

### PR DESCRIPTION
**Pull request by ibek**
Please merge this project ASAP. It's the complete implementation of the getting started experience.

You can test it with the following data and scenarios:

Name: Ivo
SSN: 123456789
Income: 60000
Locale: Rural
Property Sale Price: 50000
Age: 8
Down payment: 30000
Amort: 10

=> exp Mortg: 100 000

Income 150000, Prop: 250000, Age: 3, Urban => Morg: 200000

groups:
- broker, approver, manager

1a) Qualify - approver - inlimit checked
2a) Final Approval - manager - complete task
Process instance completed

1b) Qualify - approver - inlimit unchecked
2b) Increase down payment - broker - incdownpayment checked
3b) Qualify - approver - inlimit checked
4b) Final Approval - manager - complete task

Invalid:
1c) Downpayment : >= prop sale price
2c) Correct data - broker - downpayment < prop sale price

### CODE REVIEW

**Comment by ibek** [comment]
@krisv @mbiarnes  Hi, could you make sure this PR is merged for the next build? The deadline is on Thursday AFAIK. Thanks

**Comment by krisv** [comment]
ok to test

**Comment by ibek** [comment]
Please wait with the merge, there is an error .. the mortgage amount is not calculated

**Comment by ibek** [comment]
@krisv The mortgage calculation was fixed, please merge the PR if everything is fine

**Comment by krisv** [comment]
@ibek can you also do a PR for master?

**Pull request merged**
