### PR TITLE
JBPM-7124: KIE Playground examples - Move to the use of Stunner as the default process editor

### PR DESCRIPTION
**Pull request by pefernan**
Copy of https://github.com/kiegroup/kie-wb-playground/pull/60

@romartin @mswiderski could you please review?

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
do we have all case mgmt features supported in stunner? I mean case prefix, roles case file variables etc?

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@mswiderski I think @manstis is the one to answer...

**Comment by manstis** [comment]
@pefernan Please see https://github.com/kiegroup/kie-wb-distributions/pull/631 for the ```properties``` files containing the (new) Designer permission settings. Please note there are different ```properties``` files for Community and Production... It is currently enabled for Community and disabled for Product.

**Comment by manstis** [comment]
@mswiderski Case Modeller Editor is not integrated into ```kie-[drools]-wb``` at the moment.

I forget who is currently working on Case Modeller ("jary" on IRC IIRC).

**Comment by manstis** [comment]
@mswiderski The last I saw of the Editor it was extremely basic so I'd suspect none of what you ask is present.

**Comment by mswiderski** [comment]
in that case it does not make sense to make the order-hardware to be opened in new process editor as you won't be able to make any changes to the case definition related properties.

**Comment by pefernan** [comment]
@manstis @mswiderski so I'll revet changes on order-hardware.. gimme some minutes

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
unrelated build issues on jenkins again... last try

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Pull request merged**
