### PR TITLE
JBPM-8464 - Migrate itorders main case to use new process designer

### PR DESCRIPTION
**Pull request by krisv**
- updating itorders main case to use new process designer

### CODE REVIEW

**Comment by krisv** [comment]
@romartin @mswiderski can you guys review? @romartin can you also find someone from QE to take a look?

**Comment by mswiderski** [comment]
@krisv I tried it and there is one data output missing for Manager approval task, see here 
https://github.com/kiegroup/kie-wb-playground/blob/master/itorders/src/main/resources/org/jbpm/demo/itorders/orderhardware.bpmn2#L240-L243

and more severe is whenever you made any change to the process and save it, it is not saved and it shows this validation error:

```
Validation failed.
Reason/s: 
[Identifier: _FC2101F7-B077-4206-9BE0-42F7D7AA85E4] 
(WARNING) The diagram must contain a minimum of 1 occurrences for any of the following roles '[Startevents_all]'. Currently found 0 occurrence/s
[Identifier: _AA530384-90A4-4FF9-86F3-4ECBC3F54718] 
(WARNING) 'executionSet.signalRef.value' must match "^$|[a-zA-Z0-9_]+|[#]{1}[{]{1}[a-zA-Z0-9_]+[.]*[a-zA-Z0-9_]+[}]{1}|[#]{1}[{]{1}[a-zA-Z0-9_]+[.]*[a-zA-Z0-9_]+[(]{1}[a-zA-Z0-9._",\s]+[)]{1}[}]{1}"
[Identifier: _1D638C53-0084-4FE4-B358-0F400D99174A] 
(WARNING) 'executionSet.signalRef.value' must match "^$|[a-zA-Z0-9_]+|[#]{1}[{]{1}[a-zA-Z0-9_]+[.]*[a-zA-Z0-9_]+[}]{1}|[#]{1}[{]{1}[a-zA-Z0-9_]+[.]*[a-zA-Z0-9_]+[(]{1}[a-zA-Z0-9._",\s]+[)]{1}[}]{1}"
```

**Comment by romartin** [comment]
Hey @mswiderski !

Some feedback about the validation issues you mention:
* Yeah at least the first message is not correct for cases. There already exists [JBPM-8450](https://issues.jboss.org/browse/JBPM-8450) for it. 
* Anyway all validation issues are warnings, which should ALLOW saving the process anyway. Lemme try to save this process now, but if it's actually not saving, it's a bug. Will give you feedback in a while

Thx!

**Comment by romartin** [comment]
@mswiderski yeah just imported the attached bpmn file into a case project - I'm able to update and save it, as commented, some validation warns appear, but the process is being saved. Am I doing something wrong? can you plz confirm? Thx in advance!

**Comment by mswiderski** [comment]
I cloned this project into workbench, added missing data output into Manager Approval user task and tried to save it ... reopened it and the data output was not there. Will check again on 7.21.0 later today or over weekend

**Comment by romartin** [comment]
@mswiderski yeah the data output issue could be there, I was talking about the validation issues that appear as well (cardinality, etc)

**Comment by mswiderski** [comment]
just tried on 7.21.0.Final and the issue is exactly the same - added data output to Manager Approval task is not saved and results with this popups

image

so apparently the bpmn2 is not saved - tried both chrome and Firefox

**Comment by krisv** [comment]
@romartin @mswiderski the issue with the output association is not that it's not saving, but that the output association is lost.  This seems to be because the output parameter "approved_" is mapped twice (once to a process variable approved, once to a case file variable approved) and the parser seems to be losing one of them.  @romartin can you create a JIRA for this and have someone take a look at this?
The other thing I noticed is that currently the properties are not showing me the case file variable section, this seems to be because the project itself is not a case project.  I probably should amend a fix to the PR to update the project to case project (add a .caseproject file in itorders folder).

**Comment by romartin** [comment]
@krisv @mswiderski yep sure guys, lemme summarize the different issues here and provide the right tickets. Give me a while and will provide your the different links so we can define the priorities etc. Thanks and sorry for the inconveniences.

**Comment by romartin** [comment]
@krisv thx for the feedback - looking at old releases and the legacy designer it declares twice the var, so if I understand correcly the issue is not on the stunner code itself, the issue is on the process declaration which actually defines twice the output variable `approved_`, is that correct? If so, which is the right association to keep there? Also it means the fix will be done on the process declaration, so why not just keeping the [JBPM-8464](https://issues.jboss.org/browse/JBPM-8464) for this but just reassigning it, probably even reusing this PR?
Thanks!

**Comment by romartin** [comment]
@krisv also it's true we could fix the stunner marshallers to avoid this siutation in some way, but anyway we sholud provide some feedback about duplicate entries somewhere? Thsi could even be considered an improvement and jsut fix the process declaration, to make this case work again in Stunner...

**Comment by mswiderski** [comment]
@romartin I don't see anything wrong with mapping of the same data output to different process variables and in fact in this example it was actually done on purpose - first mapping it to process variable and then to case file variable

**Comment by krisv** [comment]
@romartin agree with Maciej, there's nothing wrong with having multiple outgoing mappings from the same output parameter.  So I think this needs a fix in stunner, not in the itorders process.

**Comment by romartin** [comment]
Ok thanks @mswiderski @krisv 
Finally in order to complete [JBPM-8464](https://issues.jboss.org/browse/JBPM-8464) (this PR) we also have to fix [JBPM-8450](https://issues.jboss.org/browse/JBPM-8450) and [JBPM-8489](https://issues.jboss.org/browse/JBPM-8489).
I think would be probably a good idea to wait until the blocking issues here are fixed, before moving this example to Stunner. WDYT?
Thanks!

**Comment by krisv** [comment]
@romartin what's the ETA on these two issues?  I think we can wait a little longer, I already checked with docs and they can proceed for now.

**Comment by romartin** [comment]
Hey @krisv 
Just added estimates to both [JBPM-8450](https://issues.jboss.org/browse/JBPM-8450) and [JBPM-8489](https://issues.jboss.org/browse/JBPM-8489). The first one should be farily easy (looks it's jsut missing some rule to define on the domain), the second one I think it's also easy, but it requires fixing the marshallers and tests, so added a higher estimate, although again, both looks pretty easy. Also assigned both to @Josephblt , we're all busy on the team.. is it good for you @Josephblt ?
@krisv so let's also wait for this merge until both fixed, right?
Thx

**Comment by krisv** [comment]
@romartin reviving this PR as this is still something that we need to do.  Can you comment on whether the issues encountered were already fixed (or can be fixed for next release still)?

**Comment by romartin** [comment]
Hey @krisv 

Yeah I have those in mind... I try always to keep those in top of backlog to address ASAP, but we're not spending much time on bug fixing yet.

So just added on top of the backlog now. As those are critical, I guess can be fixed during next weeks, and probably even being part of next RHPAM 7.6 release, but it depends on many things yet..

Screenshot from 2019-11-04 23-34-30

Is that good enough for you? Anyway, having those visible on the backlog, during next Stunner's call we can focus again here...

Thx!

**Comment by krisv** [comment]
@romartin I guess I need to decide asap if we still want to update the case mgmt example to stunner for 7.6, there's not much time left.  Note that I could try to update the example to not use double output mapping of process variable (use a script instead, to avoid one of the issues), the validation error is annoying but does not prevent the user from continuing.  Should we just do the update (and live with this limitation)?

**Comment by romartin** [comment]
Hey @krisv 

Well I don't have yet tested what you mention, so I don't have all the detail as you... if you think that's not a blocker and we can live with that, which I'm also agree in case we're talking only about "wrong" notifications, I'm also fine with it.

Anyway that couple of issues that are causing this are the next ones to address, so if this week we've some time probably those will be included in the next RHPAM release, but I prefer not promise it yet because we're still trying to close the tasks first.

Thx!

**Comment by krisv** [comment]
@romartin @mswiderski I've updated the example to include a .caseproject and replaced the double output mapping to using an on-exit script to set the case variable (to work around https://issues.jboss.org/browse/JBPM-8489).  If I do that, currently only https://issues.jboss.org/browse/JBPM-8450 is still causing some issues, it seems the start event validation is fixed but stunner is still complaining about using a colon in the signal name.  It however is just a validation warning and does not prevent the process from being saved and it seems to work correctly.  While Roger and team work on still fixing those issues, do you agree we can migrate the itorders example to start using stunner now?

**Comment by mswiderski** [comment]
as long as it works then I am fine with moving to stunner based

**Comment by krisv** [comment]
@romartin thinking about it more, it works but customers wouldn't be able to create it from scratch as the tool prevents you from entering (what it thinks are) invalid signal names.  Is that something that could still be addressed, basically loosen the restrictions there so we can at least use colon and spaces too (not sure why it's strongly restricted right now, as I don't think the engine cares, so as long as the parser can handle it it should be fine).

**Comment by romartin** [comment]
Ok @krisv so you mean just disabling the "client side" validation on the field? So users will be able to add the signal names and the validation will be done server side (by the engine), is that ok? 
If so, I think @treblereel could do this during tomorrow and try to create a quick PR for it. Does that works for you @krisv @treblereel ? If so, can you please create a ticket @krisv with the rigth description and I'll assign to @treblereel , let's see if we can have this ready for the release...

**Comment by krisv** [comment]
@romartin I updated https://issues.jboss.org/browse/JBPM-8450 to reflect this (it was already describing this issue).

**Comment by romartin** [comment]
Hey @LuboTerifaj 
About the first error message that you mention, which talks about `"The content of element 'bpmn2:ioSpecification' is not complete"`, it should be alreday fixed by [JBPM-8680](https://issues.jboss.org/browse/JBPM-8680), probably this PR is not properly rebased yet?

**Comment by krisv** [comment]
@LuboTerifaj I agree on the signal names validation issue, but this is actually a limitation of stunner that will be addressed in https://issues.jboss.org/browse/JBPM-8450 but will not make 7.6.  This does not block the user from continuing though.  The problem however is that he cannot recreate the same from scratch though.  I'm reluctant on changing the naming as I fear this might impact the UI application we have built on top.
I'm not sure the task assignments are redundant, they could be used by the UI application as well.  The task sizes are different to accommodate some having longer names and having the name shown in a nice way in stunner.  The other issues you raised are things we should probably track but imho aren't critical and specifically related to this sample.  If we want this included in 7.6 I don't think we have time to address these non-critical issues.
So I guess we have to decide, can we include this now as is?  The only real limitation imho is the first one, related to the signal names.  It would mean that if customers would recreate this from scratch, we should recommend to use node names without spaces or special characters to work around this. @michelehaglund would this be acceptable?  Maybe the fix can be prioritized for 7.5.1 to minimize the impact?  Or should we postpone the merge until the fix is available?

My vote would be to include it.  @LuboTerifaj @michelehaglund @ibek wdyt?

**Comment by krisv** [comment]
@michelehaglund confirmed by email she is fine with proceeding as is, so I will merge this PR and cherry-pick to 7.30.x

**Pull request merged**
